version: '3'
services:
  web:
    build: .
    volumes:
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
      - ./app:/app/app
      - ./bin:/app/bin
      - ./db/migrate:/app/db/migrate
      - ./db/schema.rb:/app/db/schema.rb
      - ./db/seeds.rb:/app/db/seeds.rb
      - ./lib:/app/lib
      - ./test:/app/test
    environment:
      DB: postgresql
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: iff
